.TH veromix 1 "May 27, 2012"
.SH NAME
veromix \- Mixer for the PulseAudio sound server
.SH SYNOPSIS
.B veromix
.SH DESCRIPTION
Veromix lets you control the volume of each application individually.
.SH SEE ALSO
Homepage: <http://code.google.com/p/veromix-plasmoid/>
.SH AUTHOR
veromix was written by Nik Lutz <nik.lutz@gmail.com>.
.PP
This manual page was written by Nik Lutz <nik.lutz@gmail.com>,
for the Debian project (and may be used by others).
